name: Generate directory listings for specific directory tree

inputs:
  path:
    required: false
    default: .
  ignored:
    required: false
    default: ''

runs:
  using: composite

  steps:
    - name: Pre tasks
      shell: bash
      run: |
        [ -d "${{ inputs.path }}/.git" ] && mv -v "${{ inputs.path }}/.git" "${{ inputs.path }}/../.git.bak"
        find "${{ inputs.path }}" -type f -name "index.html" -exec rm -fv "{}" \;
        if [ -n "${{ inputs.ignored }}" ]; then
          for OBJ in ${{ inputs.ignored }}; do
            mv -v "${{ inputs.path }}/$OBJ" "${{ inputs.path }}/../$OBJ.bak"
          done
        fi

    - name: Generate directory listings
      uses: jayanta525/github-pages-directory-listing@v4.0.0
      with:
        FOLDER: ${{ inputs.path }}

    - name: Post tasks
      shell: bash
      run: |
        find "${{ inputs.path }}" -type f -name "index.html" -exec sudo chown -fv $(id -u):$(id -g) "{}" \;
        [ -d "${{ inputs.path }}/../.git.bak" ] && mv -v "${{ inputs.path }}/../.git.bak" "${{ inputs.path }}/.git"
        if [ -n "${{ inputs.ignored }}" ]; then
          for OBJ in ${{ inputs.ignored }}; do
            mv -v "${{ inputs.path }}/../$OBJ.bak" "${{ inputs.path }}/$OBJ"
          done
        fi
