#!/bin/sh

# Drop caches, to make sure checks here are done on the updated files
sync
echo 3 > /proc/sys/vm/drop_caches

# Prioritize /opt binaries
PATH="/opt/sbin:/opt/bin:$PATH:/opt/share/pihole/polyfill"

# Fancy console output
if [ -f /opt/share/pihole/COL_TABLE ]; then
    #shellcheck source=../../dev/core/advanced/Scripts/COL_TABLE
    . "/opt/share/pihole/COL_TABLE"
else # fallback
    TICK="[✓]"
    CROSS="[✗]"
    INFO="[i]"
    OVER="\\r[K"
fi

random_number() {
    _base=$1
    _max=$2

    bash -c "echo \$(($_base + RANDOM % $_max))"
}

gravitydb_version() {
    pihole-FTL sqlite3 -ni "$1" "SELECT \"value\" FROM \"info\" WHERE \"property\" = 'version';" || echo 0
}

service_action() {
    case "$1" in
        "start")
            _str="Starting pihole-FTL service"
        ;;
        "restart")
            _str="Restarting pihole-FTL service"
        ;;
    esac

    if [ -n "$_str" ]; then
        printf "  %s %s..." "${INFO}" "$_str"

        if /opt/etc/init.d/S65pihole-FTL "$1" > /dev/null; then
            printf "%b  %b %s...\\n" "${OVER}" "${TICK}" "$_str"
        else
            printf "%b  %b %s...\\n" "${OVER}" "${CROSS}" "$_str"
        fi
    fi
}

##########

# Is this a fresh install or an upgrade?
if [ ! -f /opt/etc/pihole/pihole.toml ]; then
    fresh_install=true
    echo "  ${INFO} ${COL_BOLD}Running Pi-hole install tasks...${COL_NC}"
else
    echo "  ${INFO} ${COL_BOLD}Running Pi-hole upgrade tasks...${COL_NC}"
fi

# Show a warning when root user is not called 'root' and update the crontab file
root_user="$(id -nu 0 2> /dev/null)"
if [ "$root_user" != "root" ]; then
    echo "  ${INFO} ${COL_BOLD}${COL_YELLOW}It looks like the root user is not called 'root' - this can cause issues!${COL_NC}"
    echo "  ${INFO} Correcting username in crontab file..."

    sed "s/ root / $root_user /g" -i /opt/etc/cron.d/pihole
fi

# Make links to system files if they don't exist in /opt/etc
[ ! -f /opt/etc/hosts ] && [ -f /etc/hosts ] && ln -s /etc/hosts /opt/etc/hosts && symlinks="$symlinks /opt/etc/hosts"
[ ! -f /opt/etc/ethers ] && [ -f /etc/ethers ] && ln -s /etc/ethers /opt/etc/ethers && symlinks="$symlinks /opt/etc/ethers"
[ ! -f /opt/etc/resolv.conf ] && [ -f /etc/resolv.conf ] && ln -s /etc/resolv.conf /opt/etc/resolv.conf && symlinks="$symlinks /opt/etc/resolv.conf"
[ -n "$symlinks" ] && echo "  ${INFO} Created symlinks:${COL_BOLD}$symlinks${COL_NC}"

# Set random gravity update and updatechecker times
if [ -f /opt/etc/cron.d/pihole ] && grep -q "59 1 \|59 17 " /opt/etc/cron.d/pihole; then
    echo "  ${INFO} Setting random gravity update and updatechecker times..."

    sed "s/59 1 /$(random_number 1 58) $(random_number 3 2) /" -i /opt/etc/cron.d/pihole
    sed "s/59 17 /$(random_number 1 58) $(random_number 12 8) /" -i /opt/etc/cron.d/pihole
fi

# Set user and group used for rotating the logs by logrotate
if [ -f /opt/etc/pihole/logrotate ]; then
    log_user_group="$(stat -c '%U %G' /opt/var/log)"

    if [ -n "$log_user_group" ]; then
        echo "  ${INFO} Setting user and group in logrotate file..."

        sed "s/# su #/su $log_user_group/g;" -i /opt/etc/pihole/logrotate
    fi
fi

# Initialize pihole.toml using our starting config on fresh installs
if [ -n "$fresh_install" ] && [ -f /opt/share/pihole/dist/pihole.toml ]; then
    echo "  ${INFO} ${COL_BOLD}Creating configuration file...${COL_NC}"

    install -m 644 /opt/share/pihole/dist/pihole.toml /opt/etc/pihole/pihole.toml
fi

# Get gravity database file path
gravitydb="$(pihole-FTL --config -q files.gravity)"

# Upgrade existing gravity database if needed
if [ -n "$gravitydb" ] && [ -f "$gravitydb" ]; then
    gravitydb_version="$(gravitydb_version "$gravitydb")"
    bash /opt/share/pihole/gravity.sh --upgrade

    # Force gravity update if database version has changed
    [ "$(gravitydb_version "$gravitydb")" != "$gravitydb_version" ] && gravitydb_upgraded=true
fi

# Check if service was running before the package install
if [ -f /opt/tmp/pihole_was_running.tmp ]; then
    [ "$(cat /opt/tmp/pihole_was_running.tmp)" = "$(date '+%Y-%m-%d')" ] && was_running=true
    rm -f /opt/tmp/pihole_was_running.tmp
fi

# Restart the service if it's already running
if /opt/etc/init.d/S65pihole-FTL check | grep -q 'alive'; then
    service_action "restart"
elif [ -n "$was_running" ]; then # or start it if it was running before
    service_action "start"
fi

# Create adlists.list file with default blocklists if it doesn't exist
if [ ! -f /opt/etc/pihole/adlists.list ] && [ -f /opt/share/pihole/dist/adlists.list ]; then
    install -m 644 /opt/share/pihole/dist/adlists.list /opt/etc/pihole/adlists.list
fi

# Run gravity update if database was upgraded or does not exist
if [ -n "$gravitydb_upgraded" ] || { [ -n "$gravitydb" ] && [ ! -f "$gravitydb" ] ; }; then
    bash /opt/share/pihole/gravity.sh
fi

# Late fresh install tasks
if [ -n "$fresh_install" ]; then
    # Set interface to use
    if [ -z "$(pihole-FTL --config -q dns.interface)" ]; then
        # Grab first interfaces with private IP address and specific prefix
        new_interface="$(ip -o addr show up | grep -E ' (10\.[0-9]+\.[0-9]+\.[0-9]+|172\.(1[6-9]|2[0-9]|3[0-1])\.[0-9]+\.[0-9]+|192\.168\.[0-9]+\.[0-9]+)' | awk '{print $2}' | grep '^eth\|^br\|^en[opsx]\|^wlan\|^wl[px]' | head -n1)"

        if [ -n "$new_interface" ]; then
            pihole-FTL --config dns.interface "$new_interface" > /dev/null
            echo "  ${INFO} Using interface: ${COL_NC}${COL_CYAN}$new_interface${COL_NC}"
        fi
    fi

    # Set a password for the web interface
    new_password=$(tr -dc _A-Z-a-z-0-9 < /dev/urandom | head -c 8)
    pihole-FTL --config webserver.api.password "$new_password" > /dev/null # Will be automatically hashed

    echo "  ${INFO} ${COL_BOLD}${COL_GREEN}Generated password for the web interface: ${COL_NC}${COL_CYAN}$new_password${COL_NC}"
    echo "  ${INFO} It can be changed using '${COL_BOLD}pihole setpassword${COL_NC}' command."
elif [ -z "$(pihole-FTL --config -q webserver.api.pwhash)" ]; then # Show a warning if the password is not set
    echo "  ${INFO} ${COL_RED}Password for the web interface is not set - this is a security risk!${COL_NC}"
    echo "  ${INFO} ${COL_YELLOW}Please set it using '${COL_NC}${COL_BOLD}pihole setpassword${COL_NC}${COL_YELLOW}' command.${COL_NC}"
fi

# Perform a port check on new installs
if [ -n "$fresh_install" ]; then
    dns_port="$(pihole-FTL --config -q dns.port)"
    web_ports="$(pihole-FTL --config -q webserver.port | sed 's/[^0-9,]//g' | tr ',' ' ')"
    listening="$(ss --listening --numeric --tcp --udp --processes | grep -Fv '"pihole-FTL"')"
    ports_in_use=

    for port in $dns_port $web_ports; do
        if echo "$listening" | grep -qF ":$port " && ! echo "$ports_in_use" | grep -Fq " $port"; then
            ports_in_use="$ports_in_use $port"
        fi
    done

    # Show a warning if something is already listening on one of the ports
    if [ -n "$ports_in_use" ]; then
        echo "  ${INFO} ${COL_RED}The following ports are already in use:${COL_NC}${COL_CYAN}$ports_in_use${COL_NC}"
        echo "  ${INFO} ${COL_BOLD}Pi-hole might not start - check the wiki for help.${COL_NC}"
    fi
fi

# Update remote versions via updatechecker (/opt/etc/pihole/versions)
# We cannot execute it now because it calls opkg and it is running right now
{
    timeout=300
    while [ -f /opt/tmp/opkg.lock ] && [ "$timeout" -gt 0 ] ; do
        timeout=$((timeout-1))
        sleep 1
    done

    sleep 10
    bash /opt/share/pihole/updatecheck.sh
} > /dev/null 2>&1 &

exit 0
