#!/bin/sh
# https://github.com/jacklul/entware-pi-hole/
#shellcheck disable=SC2034

ENABLED=yes
PROCS=pihole-FTL
ARGS=""
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

#shellcheck disable=SC1091
. /opt/share/pihole/rc.sh

#shellcheck disable=SC1091
. /opt/etc/init.d/rc.func
