# Pi-hole configuration file
# Encoding: UTF-8
# This file is managed by pihole-FTL

[dns]
  port = 5053
  interface = "lo"
  upstreams = [
    "8.8.8.8",
    "8.8.4.4"
  ]

[webserver]
  port = "5080,[::]:5080,5443s,[::]:5443s"
