# This is not a full configuration file, just a set of initial changes.
# This file will be rewritten when pihole-FTL starts.

[dns]
  # Change DNS port as most devices will use the default port already (default is 53).
  port = 5053

# Disable NTP feature as it may conflict with system's build-in time synchronization.
[ntp]
  [ntp.ipv4]
    active = false # Disable IPv4 NTP server
  [ntp.ipv6]
    active = false # Disable IPv6 NTP server
  [ntp.sync]
    active = false # Disable NTP synchronization

[database]
  # Reduce the maximum number of days to keep the queries in the database. (default is 91)
  maxDBdays = 31

  [database.network]
    # Reduce the maximum number of days to keep the addresses in the network table. (default is 91)
    expire = 31

[webserver]
  # Change web UI ports as most devices will use the default ports already (default are 80 and 443).
  port = "5080,5443s"

  # Reduce the maximum number of threads for the webserver. (default is 50)
  threads = 10

  [webserver.api]
    # Reduce the maximum number of concurrent API sessions. (default is 16)
    max_sessions = 8

[misc]
  # Do not change the priority of the process. (default is -10)
  nice = -999
