#!/usr/bin/env bash
# 'getent hosts' - used by gravity.sh

case "$1" in
    hosts)
        nslookup "$2" && exit 0
        exit 1
    ;;
esac

echo "'getent $1' - polyfill not implemented" >&2
exit 1
