#!/usr/bin/env bash
# 'lshw -short' - used by piholeDebug.sh
#
# note: not an actual polyfill, just using it to 
# print basic system info in the debug log

case "$1" in
    -short)
        echo "System: $(uname -a)"

        if [ -f /sys/firmware/devicetree/base/model ]; then
            echo "Model: $(tr -d '\0' < /sys/firmware/devicetree/base/model)"
        elif [ -f /proc/device-tree/model ]; then
            echo "Model: $(tr -d '\0' < /proc/device-tree/model)"
        else
            echo "Model: Unknown"
        fi

        echo "Memory: $(free -h | grep 'Mem' | awk '{print $2}')"

        exit
    ;;
esac

echo "'lshw $*' - polyfill not implemented" >&2
exit 1
