#!/usr/bin/env bash
# 'tput colors' - used by COL_TABLE
# 'tput civis' - used by piholeDebug.sh
# 'tput cnorm' - used by piholeDebug.sh
# 'tput cols' - used by padd.sh
# 'tput lines' - used by padd.sh

case "$1" in
    colors)
        case "$TERM" in
            xterm-256color|screen-256color|tmux-256color|rxvt-unicode-256color)
                echo 256
                ;;
            xterm-color|screen|tmux|rxvt|xterm|linux)
                echo 8
                ;;
            vt100|vt220|vt102|dumb)
                echo 2
                ;;
            *)
                echo 0
            ;;
        esac
    ;;
    civis)
        echo -e "\e[?25l"
    ;;
    cnorm)
        echo -e "\e[?25h"
    ;;
    cols)
        stty size | cut -d' ' -f2
    ;;
    lines)
        stty size | cut -d' ' -f1
    ;;
    *)
        echo "'tput $*' - polyfill not implemented" >&2
        exit 1
    ;;
esac
