name: Apply patches and dump infos to '.version' file

inputs:
  patches_prefix:
    required: true
  git_path:
    required: false
    default: ./stage

runs:
  using: composite

  steps:
    - name: Apply patches
      shell: bash
      run: |
        bash ./scripts/patch.sh "${{ inputs.patches_prefix }}" "${{ inputs.git_path }}"

    - name: Dump infos (version, branch, commit)
      shell: bash
      run: |
        bash ./scripts/version.sh "${{ inputs.git_path }}"
