name: Check if same dev package was already built

outputs:
  cache-hit:
    value: ${{ steps.last.outputs.cache-hit }}

runs:
  using: composite

  steps:
    - name: Create hash of .versions file
      id: hash
      shell: bash
      run: |
        [ ! -f ./.versions ] && { echo "Error: ./.versions file not found."; exit 1; }
        echo "HASH=$(sha1sum ./.versions | awk '{print $1}')" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT

    - uses: actions/cache/restore@v4
      id: last
      with:
        path: ./.versions
        key: last-dev-versions-${{ steps.hash.outputs.HASH }}
        fail-on-cache-miss: false
        lookup-only: true

    - uses: actions/cache/save@v4
      if: steps.last.outputs.cache-hit != 'true'
      with:
        path: ./.versions
        key: last-dev-versions-${{ steps.hash.outputs.HASH }}
