name: Save repository version infos

inputs:
  git_path:
    required: false
    default: ./stage

runs:
  using: composite

  steps:
    - name: Dump repository version infos
      shell: bash
      run: bash ./scripts/version.sh "${{ inputs.git_path }}"
