name: Check upstream for updates

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  ENV_FILE: ./build.env

jobs:
  check:
    concurrency: check
    runs-on: ubuntu-latest
    continue-on-error: true

    outputs:
      CORE_HASH: ${{ steps.new-hashes.outputs.CORE_HASH }}
      WEB_HASH: ${{ steps.new-hashes.outputs.WEB_HASH }}
      FTL_HASH: ${{ steps.new-hashes.outputs.FTL_HASH }}
      CORE_TAG: ${{ steps.hashes-have-tags.outputs.CORE_TAG }}
      WEB_TAG: ${{ steps.hashes-have-tags.outputs.WEB_TAG }}
      FTL_TAG: ${{ steps.hashes-have-tags.outputs.FTL_TAG }}
      STATUS: ${{ steps.status.outputs.RESULT }}

    steps:
      - name: Checkout own repository
        uses: actions/checkout@v4
        #with:
        #  ref: develop

      - name: Set branches to pull
        id: branches
        run: |
          export $(grep -v '^#' ${{ env.ENV_FILE }} | xargs -d '\n')
          echo "CORE=$CORE_BRANCH" >> $GITHUB_OUTPUT
          echo "WEB=$WEB_BRANCH" >> $GITHUB_OUTPUT
          echo "FTL=$FTL_BRANCH" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Checkout pi-hole/pi-hole repository
        uses: actions/checkout@v4
        with:
          repository: pi-hole/pi-hole
          ref: ${{ steps.branches.outputs.CORE }}
          path: ./dev/core

      - name: Checkout pi-hole/web repository
        uses: actions/checkout@v4
        with:
          repository: pi-hole/web
          ref: ${{ steps.branches.outputs.WEB }}
          path: ./dev/web

      - name: Checkout pi-hole/FTL repository
        uses: actions/checkout@v4
        with:
          repository: pi-hole/FTL
          ref: ${{ steps.branches.outputs.FTL }}
          path: ./dev/FTL

      - name: Set old hashes
        id: old-hashes
        run: |
          echo "CORE_HASH=$(sed -n 's/^CORE_REF=\([[:alnum:]]*\)\s*$/\1/p' ${{ env.ENV_FILE }})" >> $GITHUB_OUTPUT
          echo "WEB_HASH=$(sed -n 's/^WEB_REF=\([[:alnum:]]*\)\s*$/\1/p' ${{ env.ENV_FILE }})" >> $GITHUB_OUTPUT
          echo "FTL_HASH=$(sed -n 's/^FTL_REF=\([[:alnum:]]*\)\s*$/\1/p' ${{ env.ENV_FILE }})" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Set new hashes
        id: new-hashes
        run: |
          echo "CORE_HASH=$(git -C ./dev/core rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "WEB_HASH=$(git -C ./dev/web rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "FTL_HASH=$(git -C ./dev/FTL rev-parse HEAD)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: Old hashes are not empty
        id: hashes-are-not-empty
        if: ${{ steps.old-hashes.outputs.CORE_HASH != '' && steps.old-hashes.outputs.WEB_HASH != '' && steps.old-hashes.outputs.FTL_HASH != '' }}
        run: echo "RESULT=ok" >> $GITHUB_OUTPUT

      - name: At least one hash is different
        id: hashes-are-different
        if: ${{ steps.hashes-are-not-empty.outputs.RESULT == 'ok' && ( steps.old-hashes.outputs.CORE_HASH != steps.new-hashes.outputs.CORE_HASH || steps.old-hashes.outputs.WEB_HASH != steps.new-hashes.outputs.WEB_HASH || steps.old-hashes.outputs.FTL_HASH != steps.new-hashes.outputs.FTL_HASH ) }}
        run: echo "RESULT=ok" >> $GITHUB_OUTPUT

      - name: Check if each hash contains a tag
        id: hashes-have-tags
        if: ${{ steps.hashes-are-different.outputs.RESULT == 'ok' }}
        run: |
          CORE_TAG=$(git ls-remote --tags https://github.com/pi-hole/pi-hole | grep "${{ steps.new-hashes.outputs.CORE_HASH }}" | awk '{print $2}' | sed 's/refs\/tags\///')
          WEB_TAG=$(git ls-remote --tags https://github.com/pi-hole/web | grep "${{ steps.new-hashes.outputs.WEB_HASH }}" | awk '{print $2}' | sed 's/refs\/tags\///')
          FTL_TAG=$(git ls-remote --tags https://github.com/pi-hole/FTL | grep "${{ steps.new-hashes.outputs.FTL_HASH }}" | awk '{print $2}' | sed 's/refs\/tags\///')
          if [ "$CORE_TAG" != "" ] && [ "$WEB_TAG" != "" ] && [ "$FTL_TAG" != "" ]; then
            echo "CORE_TAG=$CORE_TAG" >> $GITHUB_OUTPUT
            echo "WEB_TAG=$WEB_TAG" >> $GITHUB_OUTPUT
            echo "FTL_TAG=$FTL_TAG" >> $GITHUB_OUTPUT
            cat $GITHUB_OUTPUT
            echo "RESULT=ok" >> $GITHUB_OUTPUT
          fi

      - name: Apply patches (core)
        id: patch-core
        if: ${{ steps.hashes-have-tags.outputs.RESULT == 'ok' }}
        uses: ./.github/actions/patch
        with:
          patches_prefix: core
          git_path: ./dev/core

      - name: Apply patches (web)
        id: patch-web
        if: ${{ steps.hashes-have-tags.outputs.RESULT == 'ok' }}
        uses: ./.github/actions/patch
        with:
          patches_prefix: web
          git_path: ./dev/web

      - name: Apply patches (FTL)
        id: patch-FTL
        if: ${{ steps.hashes-have-tags.outputs.RESULT == 'ok' }}
        uses: ./.github/actions/patch
        with:
          patches_prefix: FTL
          git_path: ./dev/FTL

      - name: Set up Docker Buildx
        id: setup-docker-buildx
        if: ${{ steps.patch-FTL.outcome == 'success' }}
        uses: docker/setup-buildx-action@v3

      - name: Build and test FTL
        id: build-FTL
        if: ${{ steps.setup-docker-buildx.outcome == 'success' }}
        uses: docker/build-push-action@v5
        env:
          platform: linux/amd64
        with:
          platforms: ${{ env.platform }}
          pull: true
          push: false
          context: ./dev/FTL
          target: result
          file: ./dev/FTL/.github/Dockerfile
          outputs: |
            type=tar,dest=./dev/FTL/build.tar
          build-args: |
            "CI_ARCH=${{ env.platform }}"
            "GIT_BRANCH=${{ steps.branches.outputs.FTL }}"
            "GIT_TAG="

      - name: Set ok status
        if: ${{ steps.patch-core.outcome == 'success' && steps.patch-web.outcome == 'success' && steps.patch-FTL.outcome == 'success' && steps.build-FTL.outcome == 'success' }}
        id: status
        run: echo "RESULT=ok" >> $GITHUB_OUTPUT

  update:
    concurrency: update
    needs: [check]
    if: ${{ needs.check.outputs.STATUS == 'ok' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout own repository
        uses: actions/checkout@v4
        #with:
        #  ref: develop

      - name: Replace hashes in env file
        run: |
          sed 's/CORE_REF=.*$/CORE_REF=${{ needs.check.outputs.CORE_HASH }}/' -i ${{ env.ENV_FILE }}
          sed 's/WEB_REF=.*$/WEB_REF=${{ needs.check.outputs.WEB_HASH }}/' -i ${{ env.ENV_FILE }}
          sed 's/FTL_REF=.*$/FTL_REF=${{ needs.check.outputs.FTL_HASH }}/' -i ${{ env.ENV_FILE }}

      - name: Is repository modified?
        id: modified
        run: echo "RESULT=$([ "$(git diff)" != "" ] && echo yes || echo no)" >> $GITHUB_OUTPUT

      - name: Create suggested tag name
        if: ${{ steps.modified.outputs.RESULT == 'yes' }}
        id: tag
        run: |
          bash -c '
            REVISION=0
            TAG=""
            LIMIT=100
            while [ "$TAG" = "" ] || git tag | grep -q "$TAG"; do
                REVISION=$((REVISION+1))
                TAG=$(date +%Y.%m.%d)-$REVISION
                LIMIT=$((LIMIT-1))
                [ $LIMIT -le 0 ] && exit 1
            done
            echo "RESULT=$TAG" >> $GITHUB_OUTPUT
            echo "$TAG"
          '

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        if: ${{ steps.tag.outputs.RESULT != '' && (github.event_name == 'schedule' || github.ref_name == 'master') }}
        with:
          branch: auto-update
          base: develop
          delete-branch: true
          sign-commits: true
          commit-message: 'Update release build refs'
          title: 'Update package to ${{ steps.tag.outputs.RESULT }}'
          body: |
            Release tag: `${{ steps.tag.outputs.RESULT }}`
            Core version: [${{ needs.check.outputs.CORE_TAG }}](https://github.com/pi-hole/pi-hole/releases/tag/${{ needs.check.outputs.CORE_TAG }})
            Web version: [${{ needs.check.outputs.WEB_TAG }}](https://github.com/pi-hole/web/releases/tag/${{ needs.check.outputs.WEB_TAG }})
            FTL version: [${{ needs.check.outputs.FTL_TAG }}](https://github.com/pi-hole/FTL/releases/tag/${{ needs.check.outputs.FTL_TAG }})
